const sn1 = new sticky()
sn1.create()
sn1.changeColor("green")
sn1.changeTitle("Question 1: Introduce yourself")
sn1.changePosition(300, 300)
sn1.changeSize(400, 300)
sn1.changeFontSize(20)

const sn2 = new sticky()
sn2.create()

const sn3 = new sticky()
sn3.create()
sn3.changePosition(300, 700)
sn3.changeColor("lightBlue")
sn3.changeFontColor("black")
sn3.changeTitle("Write down what you think")